dist: trusty
language: java
sudo: false

cache:
  directories:
  - "$HOME/.m2"
before_cache:
- rm -rf $HOME/.m2/repository/net/lobster

jobs:
  include:
  - stage: test
    jdk: oraclejdk8
    script: mvn -q -v
    env: CHECK_SEMANTIC_VERSION=true

branches:
  only:
  - master
#-DskipTests=true
#mvn -q	| --quiet 控制Maven的日志级别,仅仅显示错误;
#mvn -Pxxx 	激活 id 为 xxx的profile (如有多个，用逗号隔开);zcgtravis
after_success:
  - mvn jacoco:report
  - mvn coveralls:report -DrepoToken="${COVERALLS_TOKEN}"

env:
  global:
    - secure: "flMbUB2pd19JRyW0LUvElf3ISK25aZiPN"